from getpass import getpass
import os
import time

def inicio():
         while True:
              print("")
              os.system('clear')
              print("\033[1;31mB                      B\033[0m")
              time.sleep(1)
              os.system('clear')
              print("\033[1;32mBY                     BY\033[0m")
              time.sleep(1)
              os.system('clear')
              print("\033[1;33mBY:                     BY:\033[0m")
              time.sleep(1)
              os.system('clear')
              print("\033[1;34mBY: V                     BY: D\033[0m")
              time.sleep(1)
              os.system('clear')
              print("\033[1;35mBY: VI                     BY: DE\033[0m")
              time.sleep(1)
              os.system('clear')
              print("\033[1;36mBY: VIP                      BY: DEA\033[0m")
              time.sleep(1)
              os.system('clear')
              print("\033[1;37mBY:VIPL                     BY: DEAD\033[0m")
              time.sleep(1)
              os.system('clear')
              print("\033[1;31mBY:VIPLA                     BY:DEADS\033[0m")
              time.sleep(1)
              os.system('clear')
              print("\033[1;32mBY: VIPLAY                     BY: DEADSEC\033[0m")
              time.sleep(1)
              os.system('clear')
              print("")
              print("")  
              print('\033[1;31m     ______   _        _______  _______  _ ')
              print('\033[1;31m    (  ___ \ ( \      (  ___  )(  ____ \| \    /\ ')
              print('\033[1;31m    | (   ) )| (      | (   ) || (    \/|  \  / / ')
              print('\033[1;31m    | (__/ / | |      | |   | || |      |  (_/ / ')
              print('\033[1;32m    |  __ (  | |      | |   | || |      |   _ ( ')
              print('\033[1;32m    | (  \ \ | |      | |   | || |      |  ( \ \ ')
              print('\033[1;32m    | )___) )| (____/\| (___) || (____/\|  /  \ \ ')
              print('\033[1;32m    |/ \___/ (_______/(_______)(_______/|_/    \/')
              print("")
              print("")
              print("\033[1;31m @@@@@                                        @@@@@ \033[0m")
              print("\033[1;31m @@@@@@@                                     @@@@@@@\033[0m")
              print("\033[1;31m @@@@@@@           @@@@@@@@@@@@@@@           @@@@@@@ \033[0m")
              print("\033[1;31m  @@@@@@@@       @@@@@@@@@@@@@@@@@@@        @@@@@@@@\033[0m")
              print("\033[1;31m      @@@@@     @@@@@@@@@@@@@@@@@@@@@     @@@@@\033[0m")
              print("\033[1;31m        @@@@@  @@@@@@@@@@@@@@@@@@@@@@@  @@@@@\033[0m")
              print("\033[1;31m          @@  @@@@@@@@@@@@@@@@@@@@@@@@@  @@\033[0m")
              print("\033[1;31m             @@@@@@@    @@@@@@    @@@@@@ \033[0m")
              print("\033[1;31m             @@@@@@      @@@@      @@@@@ \033[0m")
              print("\033[1;31m             @@@@@@      @@@@      @@@@@ \033[0m")
              print("\033[1;31m              @@@@@@    @@@@@@    @@@@@ \033[0m")
              print("\033[1;32m               @@@@@@@@@@@  @@@@@@@@@@ \033[0m")
              print("\033[1;32m                @@@@@@@@@@  @@@@@@@@@ \033[0m")
              print("\033[1;32m             @@   @@@@@@@@@@@@@@@@@   @@ \033[0m")
              print("\033[1;32m            @@@@  @@@@ @ @ @ @ @@@@  @@@@ \033[0")
              print("\033[1;32m           @@@@@   @@@ @ @ @ @ @@@   @@@@@ \033[0m")
              print("\033[1;32m         @@@@@      @@@@@@@@@@@@@      @@@@@ \033[0m")
              print("\033[1;32m       @@@@          @@@@@@@@@@@          @@@@ \033[0m")
              print("\033[1;32m    @@@@@              @@@@@@@              @@@@@ \033[0m")
              print("\033[1;32m   @@@@@@@                                 @@@@@@@ \033[0m")
              print("\033[1;32m    @@@@@                                   @@@@@ \033[0m")
              print("")
              print("")
              time.sleep(2)
              os.system("clear")
              print("\033[1;31m                     .--------. \033[0m")
              print("\033[1;31m                    / .------. \ \033[0m")
              print("\033[1;31m                   / /        \ \ \033[0m")
              print("\033[1;31m                   | |        | | \033[0m")
              print("\033[1;31m                  _| |________| |_ \033[0m")
              print("\033[1;31m                .' |_|        |_| '. \033[0m")
              print("\033[1;31m                '._____ ____ _____.' \033[0m")
              print("\033[1;31m                |     .'____'.     | \033[0m")
              print("\033[1;31m                '.__.'.'    '.'.__.' \033[0m")
              print("\033[1;31m                '.__  | LOCK |  __.' \033[0m")
              print("\033[1;31m                |   '.'.____.'.'   | \033[0m")
              print("\033[1;31m                '.____'.____.'____.' \033[0m")
              print("\033[1;31m                '.________________.' \033[0m")
              print("")
              print("")
              try:

                    INFO =str(input("\033[1;31mINFORME SEU LOGIN\033[1;32m: "))
                    print("")
                    SENHA = getpass("\033[1;31mINFORME SUA SENHA\033[1;32m: ")
                    print("")
                    print("")
                    if INFO=="viplay" and SENHA=="12345":
                       os.system("clear")
                       print("")
                       print("")
                       print("")
                       print("")
                       print("")
                       print("")
                       print("")
                       print("\033[1;32m                     .--------. \033[0m")
                       print("\033[1;32m                    / .------. \ \033[0m")
                       print("\033[1;32m                   / /         \033[0m")
                       print("\033[1;32m                   | |         \033[0m")
                       print("\033[1;32m                  _| |________ \033[0m")
                       print("\033[1;32m                .' |_|        |_| '.\033[0m")
                       print("\033[1;32m                '._____ ____ _____.' \033[0m")
                       print("\033[1;32m                |     .'____'.     | \033[0m")
                       print("\033[1;32m                '.__.'.'    '.'.__.' \033[0m")
                       print("\033[1;32m                '.__ |Unlocked|__ .' \033[0m")
                       print("\033[1;32m                |   '.'.____.'.'   |\033[0m")
                       print("\033[1;32m                '.____'.____.'____.' \033[0m")
                       print("\033[1;32m                '.________________.' \033[0m")
                       print("")
                       print("")
                       print("\033[1;31mINICIALIZANDO... \033[0m")
                       time.sleep(2)
                       os.system("clear")
                       break
                    else:
                          os.system("clear")
                          print("")
                          print("")
                          print("")
                          print("")
                          print("")
                          print("")
                          print("")
                          print("")
                          print("\033[1;31m                     .--------.\033[0m")
                          print("\033[1;31m                    / .------. \ \033[0m")
                          print("\033[1;31m                   / /        \ \ \033[0m")
                          print("\033[1;31m                   | |        | | \033[0m")
                          print("\033[1;31m                  _| |________| |_ \033[0m")
                          print("\033[1;31m                .' |_|        |_| ' \033[0m")
                          print("\033[1;31m                '._____ ____ _____.' \033[0m")
                          print("\033[1;31m                |     .'____'.     | \033[0m")
                          print("\033[1;31m                '.__.'.'    '.'.__.' \033[0m")
                          print("\033[1;31m                '.__  | LOCK |  __.' \033[0m")
                          print("\033[1;31m                |   '.'.____.'.'   | \033[0m")
                          print("\033[1;31m                '.____'.____.'____.' \033[0m")
                          print("\033[1;31m                '.________________.' \033[0m")
                          print("")
                          print("")
                          print("\033[1;31mUSUARIO OU SENHA INCORRETO! \033[0m")
                          print("")
                          print("\033[1;31mPOR FAVOR TENTE NOVAMENTE! \033[0m")
                          print("")
                          time.sleep(2)
              except Exception:
                          os.system("clear")
                          print("")
                          print("")
                          print("")
                          print("")
                          print("")
                          print("")
                          print("\033[1;31m                     .--------.\033[0m")
                          print("\033[1;31m                    / .------. \ \033[0m")
                          print("\033[1;31m                   / /        \ \ \033[0m")
                          print("\033[1;31m                   | |        | | \033[0m")
                          print("\033[1;31m                  _| |________| |_ \033[0m")
                          print("\033[1;31m                .' |_|        |_| ' \033[0m")
                          print("\033[1;31m                '._____ ____ _____.' \033[0m")
                          print("\033[1;31m                |     .'____'.     | \033[0m")
                          print("\033[1;31m                '.__.'.'    '.'.__.' \033[0m")
                          print("\033[1;31m                '.__  | LOCK |  __.' \033[0m")
                          print("\033[1;31m                |   '.'.____.'.'   | \033[0m")
                          print("\033[1;31m                '.____'.____.'____.' \033[0m")
                          print("\033[1;31m                '.________________.' \033[0m") 
                          print("\033[1;31mUSUARIO OU SENHA INCORRETO! \033[0m")
                          print("")
                          print("\033[1;31mPOR FAVOR TENTE NOVAMENTE! \033[0m")
                          print("")
                          print("")
                          time.sleep(2)
              except KeyboardInterrupt:
                          print("")
                          os.system("killall -9 com.termux")
                          os.system("clear")
                          print("")
                          print("")
                          print("")
                          print("")
                          print("")
                          print("")
                          print("")
                          print("")
                          print("\033[1;31m                     .--------.\033[0m")
                          print("\033[1;31m                    / .------. \ \033[0m")
                          print("\033[1;31m                   / /        \ \ \033[0m")
                          print("\033[1;31m                   | |        | | \033[0m")
                          print("\033[1;31m                  _| |________| |_ \033[0m")
                          print("\033[1;31m                .' |_|        |_| ' \033[0m")
                          print("\033[1;31m                '._____ ____ _____.' \033[0m")
                          print("\033[1;31m                |     .'____'.     | \033[0m")
                          print("\033[1;31m                '.__.'.'    '.'.__.' \033[0m")
                          print("\033[1;31m                '.__  | LOCK |  __.' \033[0m")
                          print("\033[1;31m                |   '.'.____.'.'   | \033[0m")
                          print("\033[1;31m                '.____'.____.'____.' \033[0m")
                          print("\033[1;31m                '.________________.' \033[0m")
                          print("")
                          print("")
                          print("")
                          print("\033[1;31mNÃO HÁ LOGIN! \033[0m")
                          print("")
                          print("\033[1;31mPOR FAVOR TENTE NOVAMENTE! \033[0m")
                          print("")
                          time.sleep(2)
inicio()
